### ISSUE TITLE
go-libjpeg integration

### ISSUE THREAD

**Issue by harukasan** [pixiv/go-libjpeg#52]
## Purpose

We are now working with two LibJPEG bindings (public go-libjpeg and the another private one).
The issue aims to integrate these projects.

## TODO

- [ ] 1. Backporting error handling to go-libjpeg
- [ ] 2. Make public low-level decoding/encoding functions
- [ ] 3. Delete the private one

## Related issues

- #50
- #51
- #47

**Comment by scaszoo** [comment]
Hi :) Any chance the enhanced LibJPEG bindings gonna be finished? :) I'm curious what enhancements await us :) Thanks for you efforts....

**Comment by scaszoo** [comment]
@harukasan and @unak I'm curious still. Would it be possible to publish the results as far as you got (as WIP) or maybe make the private version available? :-)
Cheers!

**Comment by scaszoo** [comment]
Just kindly asking again @harukasan  and @unak  :) Would you be willing to publish the work in progress and/or the private libjpeg binding version? :)
